### ISSUE TITLE
Upgrade libgdx version, possibly change backend from lwjgl2 to lwjgl3

### ISSUE THREAD

**Issue by Avalancs** [MovingBlocks/DestinationSol#312]
This is a proposition to upgrade libgdx versions, and possibly the rendering backend in the future.
Destination Sol is currently using libgdx 1.7.0. The full changelog for libgdx can be seen here: https://github.com/libgdx/libgdx/blob/master/CHANGES

Main points for upgrading to libgdx 1.9.9:
Pros:
* reimplementation of freetype which makes fonts look much better on low resolution
* newer versions of bullet and robovm
Cons:
* Android api level 9 requirement. But based on https://developer.android.com/about/dashboards/ this should not be a problem in 2018

The proposal to change the backend is the multi-monitor support which could pontentially fix #40, and the access to vulkan and opencl apis for wizards.

Upgrading only libgdx can be done with minor modifications, which can already be tested on https://github.com/Avalancs/DestinationSol/tree/libgdxUpgrade

**Comment by BenjaminAmos** [comment]
Is this still neded, or is someone else taking care of it? As long as no duplication of work has been committed, then I would gladly do both upgrades (LibGDX v1.9.8 and LWJGL3).

Some initial work to get it mostly working can be found on the "[libgdx-v1.9.8-upgrade](https://github.com/BenjaminAmos/DestinationSol/tree/libgdx-v1.9.8-upgrade)" and "[lwjgl3-upgrade](https://github.com/BenjaminAmos/DestinationSol/tree/lwjgl3-upgrade)" branches of my fork (many thanks to @Avalancs for the reference). I can submit these as pull requests if this has not already been done. I would prefer to have these changes so that I can simplify #355 anyway.

**Comment by vampcat** [comment]
No work on has done on this front since this issue was created, so any work would be appreciated :)
