### ISSUE TITLE
Inventory behaves weird

### ISSUE THREAD

**Issue by ererbe** [MovingBlocks/DestinationSol#316]
### I tried to play the game and use the Inventory, but the inventory behaved really weird

- picked up items don't show up, just when you press talk and buy, and then just the first time
- bought items show up
- dying resets my save file to the last one, not the actual (the last ship)
- when I die, I drop items that are not showed in the inventory but were collected.

### How to reproduce

* Step 1: use latest develop
* Step 2: starting using `gradlew run`
* Step 3: play and try to use the inventory (after collecting a drop)

### Log details and game version
Latest develop (commit e92474b)
### Computer details
Windows 7 64 bit.
16GB Ram.
AMD graphic card.

I made a small video with all the bug(s): https://www.youtube.com/watch?v=qnd9dsAyo_M&feature=youtu.be
I also hope my english was not that bad.

**Comment by Cervator** [comment]
Update: @Avalancs is working on a fix for this, the issue remains quirky to puzzle out a good approach for. One addition fun part I just discovered: since the "Talk" screen is available anywhere (it really shouldn't be! That's another bug - it should only be available when you're docked and tied to whatever shop that is) you can see the items you _did_ pick up on the buy screen _and buy them_ - at which point they're now in your inventory properly ;-)
