### ISSUE TITLE
Cannot drop arbitrary money, only increments of pre-defined values

### ISSUE THREAD

**Issue by Avalancs** [MovingBlocks/DestinationSol#430]
As the discussion from https://github.com/MovingBlocks/DestinationSol/pull/428 Right now money under 10 (the smalles recognized increment) is discarded when a ship dies and throws out money.

I think the icon for the smallest money should handle 1-10. Since the amount is already stored next to the icon in the MoneyItem class, and the exact amount is saved on the player, this should require minimal code changes.

**Comment by Malanius** [comment]
I might try poking into this, seems easy enough to get back to the code base after a year :)

**Comment by Malanius** [comment]
So, I've looked on this, the problem is in `ItemManager#moneyToItems` and how the while loop is structured. This is easy to fix to allow to drop amounts less than 10 with a small icon (but it would be same for amounts from 0-30). If this is OK, I can open the PR with it.

But since all money are floats and the drop size gets calculated in SolShip as a random portion of `myMoney` without any roundings, the dropped amount can be sometimes really strange, like `5.027163`.

The worst part about this is testing it since the drop is calculated in `SolShip#throwAllLoot` but is not deducted here (well doesn't make much sense for any other than player's ship), and the player money is deducted on player respawn by 25% in `SolGame#setRespawnState`...
So the idea to test it by setting up money in `prevShip.ini` < 10, dying (thanks for the awesome `die` console command!) and then picking up the dropped money didn't work out :)
Should we bring this inline for the player to drop the 25% of the money instead of the random portion?

The only way I can prove the drop of small amounts it works is with additional logging...

Any ideas or insights on how to proceed would be helpful :)
