### ISSUE TITLE
Game crashed instantly as i double clicked to launch

### ISSUE THREAD

**Issue by LaytonBaccea** [MovingBlocks/DestinationSol#442]
I ran the newest version from here, when i double clicked it crashed right away and keeps going (Tried with administrator).

Here's the log 
com.badlogic.gdx.utils.GdxRuntimeException: Couldn't load file: res/icon.png
	at com.badlogic.gdx.graphics.Pixmap.<init>(Pixmap.java:140)
	at com.badlogic.gdx.backends.lwjgl.LwjglGraphics.setupDisplay(LwjglGraphics.java:160)
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication.mainLoop(LwjglApplication.java:138)
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication$1.run(LwjglApplication.java:120)
Caused by: com.badlogic.gdx.utils.GdxRuntimeException: File not found: res\icon.png (Internal)
	at com.badlogic.gdx.files.FileHandle.read(FileHandle.java:136)
	at com.badlogic.gdx.files.FileHandle.readBytes(FileHandle.java:222)
	at com.badlogic.gdx.graphics.Pixmap.<init>(Pixmap.java:137)
	... 3 more

Thanks in advance

**Comment by NicholasBatesNZ** [comment]
What exactly did you double click to get this error? I assume that by `from here` you mean that you cloned this repo locally? Or did you download one of the releases? To run from source you need to run `gradlew run` in the terminal from the `Destination Sol` root directory.

**Comment by LaytonBaccea** [comment]
Okay got it, i'll try it.  I ran it from the sol.exe in the folder ''launcher''.

**Comment by LaytonBaccea** [comment]
Okay i ran gradlew.bat it downloaded and configured it, then it closed, i tried to run the sol.exe launcher again, crashed instantly...

**Comment by Adrijaned** [comment]
Hey @LaytonBaccea, if you are having problems running the exe, they most definitely won't be fixed by the gradlew thing - the exe is created somewhere on our server, and the bat file doesn't edit it at all, nor it can. Just to make sure we are on the same note, could you please copy paste us here somewhere the exact link you got the game from? Also, if you want to run the game using the gradlew.bat, you have to:
* Go to the directory the file is at using the file explorer
*  Type `cmd` in the address line, then press enter ![img](https://www.itechtics.com/wp-content/uploads/2018/10/cmd-using-file-explorer-e1539612304747-670x254.png)
* A terminal window should pop up, type `gradlew run` in that window, then press enter

**Comment by LaytonBaccea** [comment]
Okay it is fixed now, but now it says that it needs a libray folder with alot of .jars files.....

**Comment by NicholasBatesNZ** [comment]
@LaytonBaccea were you able to run the game? Can you be more specific about the problem please, maybe include a log?

**Comment by Cervator** [comment]
Hey @LaytonBaccea - general usage help is better to request on our Discord server in the #destination-sol channel. We can offer live guidance there instead of occasional updates on an issue here :-)

https://discord.gg/tearsology

Closing as a general support issue we can continue on chat.
