### ISSUE TITLE
Free mercenaries!

### ISSUE THREAD

**Issue by NicholasBatesNZ** [MovingBlocks/DestinationSol#542]
Hooray, free fighters for everybody! :tada: 

Or perhaps that's not so ideal...

As this [Steam report](https://steamcommunity.com/app/342980/discussions/0/2792745783002768455/) mentions, there is a mercenary available for a cost of 0 (credits, money, lootz??)

The offending mercenary is the [IK-2 Escort](https://github.com/DestinationSol/federal/blob/master/assets/ships/federalTiny/federalTiny.json) from the [Federal](https://github.com/DestinationSol/federal) module:

![](https://steamuserimages-a.akamaihd.net/ugc/1455176929803958189/D9C9B616B89A4ADBFC0B7C6A2D32C1A8080585A0/)

**Comment by BenjaminAmos** [comment]
The `IK-2 Escort` ship is missing a `hirePrice` attribute, in-case anyone wants to fix this issue in the future. Since most ships seem to omit this attribute, it might be worth changing the default value to be the same as the sell price.
https://github.com/MovingBlocks/DestinationSol/blob/6d93ffa817dbf26493c684971aa242b9c1f77d9b/engine/src/main/java/org/destinationsol/files/HullConfigManager.java#L180-L181
