### ISSUE TITLE
Logo is too big for tutorial-chan

### ISSUE THREAD

**Issue by Esnardo** [MovingBlocks/DestinationSol#573]
Issue: On the title screen on android, the logo covers the tutorial button. Contrary to my title, i think the best way to fix this is to make the buttons shorter.

Repro:
1. Open the game

V2.0.0, LGK20, Android

**Comment by BenjaminAmos** [comment]
I think this might have been fixed with #631. On the smallest screen size I could emulate, the logo seemed to just about fit. Could you possibly check if this is still the case on the latest Android build?

![Screenshot_1643456909](https://user-images.githubusercontent.com/24301287/151659866-1461a199-3f60-40d3-afdc-7913f153e668.png)

You can find an automatically built debug APK [here](https://jenkins.terasology.io/teraorg/job/DestinationSol/job/engine/job/develop/lastSuccessfulBuild/artifact/android/build/outputs/apk/debug/android-debug.apk) or build it yourself from any commit after https://github.com/MovingBlocks/DestinationSol/commit/6c6f1b23d8dcd9c832cc8665fbdbf9cadd28f54d.

**Comment by Esnardo** [comment]
Fixed!
